# Oracle Configuration
id: oracle-1

# Network Configuration
port: 5300
apiPort: 5400

# Consensus Configuration
primary: true
minSignaturesRequired: 0
peerTimeoutMs: 500

privateKey: "f0e9f1cec2d0dea1012c882451c5fc481d67b016255b21b8cd89792234d4f76e"
publicKey: "034059e641d0ceb0e84688a2a6b70cf3b8e642fe933b5d520173d5d9486b89a864"

listener:
  intervalMs: 10000

listeners:
  solana-listener:
    rpcUrl: "https://api.devnet.solana.com"
    programId: "yteDZqmquhCJwDKumf35uPqcknDn87xgcDLqdxjAigq"
    cacheTtlMs: 86400000
    directoryNodeUrlPool: "http://localhost:7740"
    blockchainRid: "CFEA611E4455A87B5C09C2BFC7FC135976DD731C50C99EADDA813B2B9EFC7E7E"

plugins:
  solana-mega-forwarder:
    solanaRpcUrl: "https://api.devnet.solana.com"
    solanaProgramId: "yteDZqmquhCJwDKumf35uPqcknDn87xgcDLqdxjAigq"
    directoryNodeUrlPool: "http://localhost:7740"
    blockchainRid: "CFEA611E4455A87B5C09C2BFC7FC135976DD731C50C99EADDA813B2B9EFC7E7E"

# Peer Configuration
peers:
  # - oracleId: oracle-2
  #   address: localhost:5301
  #   publicKey: "02a07e7a2ad6eeb84c200642bae1aa279d9141ccc22046fc006466ac4298ca2e45"

  # - oracleId: oracle-3
  #   address: localhost:5302
  #   publicKey: "03fa2b4c06e4b94f19035883eefb5352505effa7e598bca010ff52a1211a2a59ca"
