# Oracle Configuration
id: oracle-2

# Network Configuration
port: 5301
apiPort: 5401

# Consensus Configuration
primary: false
minSignaturesRequired: 2
peerTimeoutMs: 500

privateKey: "65fdf663f974c4fc0354d37a1e6432dd83c1ac417a7d8c1476031398ba7d0ec9"
publicKey: "02a07e7a2ad6eeb84c200642bae1aa279d9141ccc22046fc006466ac4298ca2e45"

listeners:
  solana-listener:
    rpcUrl: "http://localhost:8899"
    programId: "9DB7JmEH2xksZK265x8ucZH2yYh2Uh4PzcF9CkgaPxQW"
    cacheTtlMs: 86400000

plugins:
  solana-mega-forwarder:
    solanaRpcUrl: "http://localhost:8899"
    solanaProgramId: "9DB7JmEH2xksZK265x8ucZH2yYh2Uh4PzcF9CkgaPxQW"
    directoryNodeUrlPool: "https://node0.testnet.chromia.com:7740"
    blockchainRid: "136B54211863D0CC6239E002F6726940CB3D849C279C0B14459A00963F6B3CEC"
  solana-minter:
    solanaRpcUrl: "http://localhost:8899"
    solanaProgramId: "9DB7JmEH2xksZK265x8ucZH2yYh2Uh4PzcF9CkgaPxQW"
    nodeUrlPool: "http://localhost:7740"
    blockchainRid: "7EB45B6E0579D96DAB6854691763942B1F73E75832974F637AE495CFA69FE502"

# Peer Configuration
peers:
  - oracleId: oracle-1
    address: localhost:5300
    supportedPlugins:
      - solana-mega-forwarder
      - solana-minter
    publicKey: "034059e641d0ceb0e84688a2a6b70cf3b8e642fe933b5d520173d5d9486b89a864"
  
  - oracleId: oracle-3
    address: localhost:5302
    supportedPlugins:
      - solana-mega-forwarder
      - solana-minter
    publicKey: "03fa2b4c06e4b94f19035883eefb5352505effa7e598bca010ff52a1211a2a59ca"
